apiVersion: apps/v1
kind: Deployment
metadata: 
    name: goserver
spec: 
    replicas: 10
    selector:
        matchLabels:
            app: server
    template: 
        metadata: 
            labels: 
                app: server
        spec:
            containers: 
                - name: goserver
                  image: mrogerius/k8s
                  ports: 
                    - containerPort: 3000

